In [2]:
import torch
print(torch.__version__)

1.6.0


In [3]:
torch.cuda.is_available()

False

In [4]:
dd = [[1,2,3], [4,5,6], [7,8,9]]
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
print(type(t))
t.shape

<class 'torch.Tensor'>


torch.Size([3, 3])

In [6]:
print(t.shape[0]) # t.shape is a list

3


In [7]:
t.reshape(1,9) # reshape to length of each axis we want 
# product of component values in reshape call must equal total number of elements in tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
import numpy as np
t = torch.Tensor()
print(t)
print(type(t))

tensor([])
<class 'torch.Tensor'>


In [9]:
# tensor attributes in pytorch in particular
print(t.dtype) # type of data it holds, default float. Tensor operations btwn tensors must hold same datatypes
print(t.device) # cpu or gpu, memory location of data. Can be distributed
print(t.layout) # 

torch.float32
cpu
torch.strided


In [10]:
# There are four main ways to make a Pytorch tensor

# creating tensors with existing data
data = np.array([1,2,3])

# 1) Tensor class contstructor - float
torch.Tensor(data)

tensor([1., 2., 3.])

In [11]:
# 2) tensor factory function - int64
torch.tensor(data).dtype

torch.int64

In [12]:
# 3) as_tensor factory function - int64
torch.as_tensor(data)

tensor([1, 2, 3])

In [13]:
# 4) from_numpy factory function - int64
torch.from_numpy(data)

tensor([1, 2, 3])

In [14]:
# Creating tensors without existing data

# identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
# zeroes tensor
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
# ones tensor
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# random numbers 0 <= x <= 1
torch.rand(2,2)

tensor([[0.3103, 0.8152],
        [0.9287, 0.6769]])

In [18]:
# What are the differences betweent the four existing-data tensor creation methods?

data = np.array([1,2,3])
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

# factory functions return an object. They allow for more dynamic object creation. 2,3,4 are all FFs. 
# FFs have lots of configuration parameters 

print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [19]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [20]:
# Constructors will convert any numerical data to their dtype (float)
# FFs will read in the data and adopt this data's own datatype. Flexible. 

data2 = np.array([1., 2., 3.])
t5 = torch.tensor(data2)
print(t5)
# see^

# or like this 
t6 = torch.tensor(data2, dtype = torch.int32)
print(t6)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)


In [21]:
# Tensor() and tensor() actually also copy the original array they were built from
# T and t copy the array into new memory. Less efficient. 
# a_t and f_np access the old data memory locations. Good for converting numpy to tensor

# So which do we use?
# Torch.tensor(data) is the best. 
# If we want to code for performance, we want torch.as_tensor(data)
# We don't really need any performance management here. 

print(t6)

tensor([1, 2, 3], dtype=torch.int32)


In [22]:
# Reshaping Operations

# 4 main operation types
# reshaping operations
# element-wise operations
# reduction operations
# access operations

t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)
# Shape = 3,4 | Rank = 2

t.shape

torch.Size([3, 4])

In [23]:
# product of shape component values = number of elements

t.numel()

# good basis for figuring out reshape dimensions

12

In [24]:
t.reshape(2,6)
t.reshape(6,2)
t.reshape(4,3)
t.reshape(12,1)
t.reshape(2,2,3)
# etc

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [25]:
# We can also change the shape of our tensors by squeezing and unsqueezing 
print(t.reshape(1,12))
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).unsqueeze(dim=0))

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]])


In [26]:
# squeeze gets rid of all dimensions equal to one. 
# unsqueeze puts them back

# these just change the rank of a tensor. 
# Flattening a tensor is making it a single vector 
print(t.reshape(2,2,3))
print(t.reshape(2,2,3).flatten())
print(t)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [27]:
# implement from scratch

def flatten(t):
    return t.reshape(1,-1).squeeze()

flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [29]:
# concatenate two tensors of the same shape with torch.cat((t1, t2), dim = 0)

# How should we flatten tensors for CNN inputs in practice then?
# Let's make a fake batch

t1 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [2,2,2,2],
    [3,3,3,3]
])
t2 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [2,2,2,2],
    [3,3,3,3]
])
t3 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [2,2,2,2],
    [3,3,3,3]
])

# A batch is a single tensor, so we need to "stack" these images into one tensor with a third dimension

t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

In [30]:
# CNN needs 4 dimensions (color channel)
t.reshape(3,1,4,4)

tensor([[[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [3, 3, 3, 3]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [3, 3, 3, 3]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [3, 3, 3, 3]]]])

In [34]:
t[0][0]

tensor([1, 1, 1, 1])

In [35]:
t.flatten() # flattens entire batch, not what we want

# we want to flatten each image individually

tensor([1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3])

In [37]:
# we want to flatten the 2,3,4 dimensions
t.flatten(start_dim=1).shape # 3 images, each with 16 total items. 

torch.Size([3, 16])

In [38]:
t.flatten(start_dim=1) # three flattened images

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3],
        [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3],
        [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]])

In [39]:
# Element wise operations are on corresponding elements in different tensors
# Same index, different tensors

t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5,6],
    [7,8]
], dtype=torch.float32)

print(t1.shape)


torch.Size([2, 2])


In [41]:
t1[0][0]

tensor(1.)

In [43]:
# elements are corresponding if they occupy the same position within the tensor
print("{} | {}".format(t1[0][0], t2[0][0]))

1.0 | 5.0


In [44]:
print("sum: {}".format(t1[0][0] + t2[0][0]))
print("multiply: {}".format(t1[0][0] * t2[0][0]))

sum: 6.0
multiply: 5.0


In [49]:
# operations can also be done on tensors as a whole, applied to each element
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [50]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [46]:
t1 + 10

tensor([[11., 12.],
        [13., 14.]])

In [48]:
t1.add(10)

tensor([[11., 12.],
        [13., 14.]])

In [51]:
t1 > 0

tensor([[True, True],
        [True, True]])

In [52]:
t1 > 1

tensor([[False,  True],
        [ True,  True]])

In [53]:
# Comparison Operations

# spits out a tensor of the same size full of 1s and 0s 
# if the comparison is true, 1
# if false, 0
t = torch.tensor([
    [1,2,0],
    [3,0,4],
    [-1,2,0]
], dtype=torch.float32)

t.ge(0)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False,  True,  True]])

In [54]:
t.le(0)

tensor([[False, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [55]:
t.gt(3)

tensor([[False, False, False],
        [False, False,  True],
        [False, False, False]])

In [56]:
t.lt(2)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [57]:
t.eq(0)

tensor([[False, False,  True],
        [False,  True, False],
        [False, False,  True]])

In [58]:
# Code for Deep Learning: ArgMax and Reduction Operations

# Reduction - reduces the # of elements within a tensor
# Performed on elements within a single tensor

t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [63]:
t.sum() # outputs a tensor

torch.Tensor

In [65]:
t.numel() # outputs an int

9

In [62]:
t.sum().numel()

1

In [66]:
# more reductions
# each of these reduces the tensor to a single-element tensor
t.mean()

tensor(0.8889)

In [67]:
t.prod()

tensor(0.)

In [72]:
t.std().prod().mean().numel()

1

In [76]:
# don't always need to reduce a tensor to one element
# sometimes we reduce just one axis
t = torch.tensor([
    [1,1,1],
    [2,2,2],
    [3,3,3]
], dtype=torch.float32)

t.sum(dim=0)

tensor([6., 6., 6.])

In [77]:
t.sum(dim=1)

tensor([3., 6., 9.])

In [3]:
t = torch.tensor([
    [1,0,0],
    [0,2,0],
    [2,1,5]
], dtype=torch.float32)

t.argmax() # argmax gives us index of max element in tensor

tensor(8)

In [4]:
t.max() # max gives us value of max element

tensor(5.)

In [8]:
t.sum(dim=1).argmax() # should return index of max summed row
# third row is max lets gooo
# each successive reduction function passes forward a new tensor

tensor(2)

In [9]:
t.sum(dim=1).max() # should return value of max summed row 8

tensor(8.)

In [10]:
t.max(dim=0) # returns max from each column

torch.return_types.max(values=tensor([2., 2., 5.]), indices=tensor([2, 1, 2]))

In [11]:
t.max(dim=1) # returns max from each row

torch.return_types.max(values=tensor([1., 2., 5.]), indices=tensor([0, 1, 2]))

In [12]:
t.argmax(dim=1) # returns max from each row

tensor([0, 1, 2])

In [13]:
t.sum(dim=1).max().item() # returns the value itself not in tensor form

8.0

In [14]:
t.mean()

tensor(1.2222)

In [15]:
t.mean(dim=0)

tensor([1.0000, 1.0000, 1.6667])

In [16]:
t.mean(dim=0).tolist()

[1.0, 1.0, 1.6666666269302368]

In [17]:
t.mean(dim=0).tolist()[1]

1.0